
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import PrivateBondsContractArtifactJson from './private_bonds/PrivateBonds.json' with { type: 'json' };
export const PrivateBondsContractArtifact = loadContractArtifact(PrivateBondsContractArtifactJson as NoirCompiledContract);


      export type TransferEvent = {
        from: AztecAddressLike
to: AztecAddressLike
amount: (bigint | number)
      }
    

/**
 * Type-safe interface for contract PrivateBonds;
 */
export class PrivateBondsContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, PrivateBondsContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): PrivateBondsContract {
    return Contract.at(address, PrivateBondsContract.artifact, wallet) as PrivateBondsContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, name: FieldLike, total_supply: (bigint | number), maturity: (bigint | number), payment_token: AztecAddressLike, trusted_escrow_class_id: FieldLike) {
    return new DeployMethod<PrivateBondsContract>(PublicKeys.default(), wallet, PrivateBondsContractArtifact, (instance, wallet) => PrivateBondsContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, name: FieldLike, total_supply: (bigint | number), maturity: (bigint | number), payment_token: AztecAddressLike, trusted_escrow_class_id: FieldLike) {
    return new DeployMethod<PrivateBondsContract>(publicKeys, wallet, PrivateBondsContractArtifact, (instance, wallet) => PrivateBondsContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PrivateBondsContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<PrivateBondsContract['methods'][M]>
  ) {
    return new DeployMethod<PrivateBondsContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      PrivateBondsContractArtifact,
      (instance, wallet) => PrivateBondsContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PrivateBondsContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(PrivateBondsContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'issuer' | 'private_balances' | 'whitelist' | 'total_supply' | 'maturity_date' | 'payment_token' | 'trusted_escrow_class_id' | 'name'> {
      return {
        issuer: {
      slot: new Fr(1n),
    },
private_balances: {
      slot: new Fr(2n),
    },
whitelist: {
      slot: new Fr(3n),
    },
total_supply: {
      slot: new Fr(4n),
    },
maturity_date: {
      slot: new Fr(5n),
    },
payment_token: {
      slot: new Fr(6n),
    },
trusted_escrow_class_id: {
      slot: new Fr(8n),
    },
name: {
      slot: new Fr(10n),
    }
      } as ContractStorageLayout<'issuer' | 'private_balances' | 'whitelist' | 'total_supply' | 'maturity_date' | 'payment_token' | 'trusted_escrow_class_id' | 'name'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** __emit_public_init_nullifier() */
    __emit_public_init_nullifier: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** add_to_whitelist(investor: struct) */
    add_to_whitelist: ((investor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** ban_from_whitelist(investor: struct) */
    ban_from_whitelist: ((investor: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(name: field, total_supply: integer, maturity: integer, payment_token: struct, trusted_escrow_class_id: field) */
    constructor: ((name: FieldLike, total_supply: (bigint | number), maturity: (bigint | number), payment_token: AztecAddressLike, trusted_escrow_class_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** distribute_private(investor: struct, amount: integer) */
    distribute_private: ((investor: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_maturity_date() */
    get_maturity_date: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_name() */
    get_name: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_supply() */
    get_total_supply: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_whitelisted(address: struct) */
    is_whitelisted: ((address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_balance_of(owner: struct) */
    private_balance_of: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** redeem(amount: integer) */
    redeem: ((amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_from(from: struct, to: struct, amount: integer, authwit_nonce: field) */
    transfer_from: ((from: AztecAddressLike, to: AztecAddressLike, amount: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_private(to: struct, amount: integer) */
    transfer_private: ((to: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { TransferEvent: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      TransferEvent: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "from",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "to",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 128
            }
        }
    ],
    "path": "PrivateBonds::TransferEvent"
},
        eventSelector: EventSelector.fromString("0xdff87100"),
        fieldNames: ["from","to","amount"],
      }
    };
  }
  
}
